// Auto generated by gulp task
// Do **not** modify manually unless you know what you're doing
/* eslint-disable */
const settings = {"HTTP_CACHE_SIZE":100,"ENABLE_DEBUG_LOGGING":true,"API_URL":"https://itunes.apple.com","MEDIA_TYPES":[{"key":"all","label":"All"},{"key":"movie","label":"Movie"},{"key":"podcast","label":"Podcast"},{"key":"music","label":"Music"},{"key":"musicVideo","label":"Music Video"},{"key":"audiobook","label":"Audiobook"},{"key":"shortFilm","label":"Short Film"},{"key":"tvShow","label":"TV Show"},{"key":"software","label":"Software"},{"key":"ebook","label":"eBook"}],"DEFAULT_QUERY_PARAMS":{"media":"all","term":""},"VERSION":"0.0.1"};
export default settings;