// Auto generated by gulp task
// Do **not** modify manually unless you know what you're doing
/* eslint-disable */
export default {"HTTP_CACHE_SIZE":100,"ENABLE_DEBUG_LOGGING":true,"API_URL":"https://itunes.apple.com"}